### ISSUE TITLE
for in的循环顺序

### ISSUE THREAD

**Issue by erichui** [ConardLi/awesome-coding-js#1]
我感觉js并不是一个有序的数据结构，而且你用for in循环并不能保证‘第一次出现’这个条件

**Comment by ConardLi** [comment]
麻烦问下说的是哪道题，我看下😄

**Comment by ConardLi** [comment]
你说的是[50.第一个只出现一次的字符](https://github.com/ConardLi/awesome-coding-js/blob/master/%E5%89%91%E6%8C%87offer/50.%E7%AC%AC%E4%B8%80%E4%B8%AA%E5%8F%AA%E5%87%BA%E7%8E%B0%E4%B8%80%E6%AC%A1%E7%9A%84%E5%AD%97%E7%AC%A6.md)这道题吧。

解法一的代码最后并不是使用for in去遍历countMap，而是使用for循环遍历原数组，然后使用countMap去判断，所以不用担心有序问题。

**Comment by erichui** [comment]
不好意思 没说清楚 第50题给出的解法是没问题的 因为限制了字符都为字母 且用的是for循环
[字符流中第一个不重复的字符](https://github.com/ConardLi/awesome-coding-js/blob/master/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%88%86%E7%B1%BB/%E5%AD%97%E7%AC%A6%E4%B8%B2/%E5%AD%97%E7%AC%A6%E6%B5%81%E4%B8%AD%E7%AC%AC%E4%B8%80%E4%B8%AA%E4%B8%8D%E9%87%8D%E5%A4%8D%E7%9A%84%E5%AD%97%E7%AC%A6.md)这道题里面最后用的for in遍历
如果字符串中出现数字就会有问题

**Comment by ConardLi** [comment]
对，你说的确实是对的：
`for in`只是在某些浏览器下会保证按照顺序输出，并不是所有浏览器。
如果字符串里有数字，就会有问题。

**Comment by ConardLi** [comment]
新的解法已更新 [字符流中第一个不重复的字符](https://github.com/ConardLi/awesome-coding-js/blob/master/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%88%86%E7%B1%BB/%E5%AD%97%E7%AC%A6%E4%B8%B2/%E5%AD%97%E7%AC%A6%E6%B5%81%E4%B8%AD%E7%AC%AC%E4%B8%80%E4%B8%AA%E4%B8%8D%E9%87%8D%E5%A4%8D%E7%9A%84%E5%AD%97%E7%AC%A6.md)
