### ISSUE TITLE
算法入门，我应该从那一章节开始看呢？？

### ISSUE THREAD

**Issue by Niofh** [ConardLi/awesome-coding-js#2]

**Comment by ConardLi** [comment]
建议先对算法和数据结构的基础做大概的了解：
数据结构都有什么分类？每种数据结构的基本特点是什么？
常规算法算法解法有几种？每种算法的解题思路是什么？
掌握了上面这些，再来按照每种具体的数据结构或算法来针对性做题，总结规律。
