### ISSUE TITLE
快速排序第二种写法代码出错

### ISSUE THREAD

**Issue by Holmesen** [ConardLi/awesome-coding-js#3]
快速排序里面的第二种写法代码里面有一处有错误。
第二行这里的
`if (end - start < 2) {
        return;
      }`
if里面应该是“end - start < 1”，不然的话当刚好有两个元素的话就无法去判断排序了。
比如这个数组“[23, 11, 5, 65, 7, 33, 2, 26]”，如果按照你的写法的话会输出“[ 2, 7, 5, 11, 23, 26, 33, 65 ]”，如果改成我那样的话就会正确输出“[ 2, 5, 7, 11, 23, 26, 33, 65 ]”

**Comment by Holmesen** [comment]
http://www.conardli.top/docs/algorithm/%E6%8E%92%E5%BA%8F/%E5%BF%AB%E9%80%9F%E6%8E%92%E5%BA%8F.html#%E5%86%99%E6%B3%952
这是地址

**Comment by ConardLi** [comment]
> 快速排序里面的第二种写法代码里面有一处有错误。
> 第二行这里的
> `if (end - start < 2) { return; }`
> if里面应该是“end - start < 1”，不然的话当刚好有两个元素的话就无法去判断排序了。
> 比如这个数组“[23, 11, 5, 65, 7, 33, 2, 26]”，如果按照你的写法的话会输出“[ 2, 7, 5, 11, 23, 26, 33, 65 ]”，如果改成我那样的话就会正确输出“[ 2, 5, 7, 11, 23, 26, 33, 65 ]”

已修复，感谢提出。
